### ISSUE TITLE
Extension not loading correctly

### ISSUE THREAD

**Issue by robrt** [cgkineo/adapt-audio#3]
Hi,

We have included adapt-audio in config.json section build.includes and added the audio control with 

```{{> audio-controls this}}

The component HTML renders correctly by HandleBars BUT it seems that no assets are loaded. No event handlers are attached to the rendered audio-controls hence causes a navigation to '#' which is the value of the href attribute when rendered.

In addition to that the referred sprite in the css can not be found in the extension itself nor in the assets catalog of the build.

Any ideas? Thanks in advance,
Robert

**Comment by moloko** [comment]
You need to attach the event handlers yourself as documented [here](../#usage)

I don't think we've used this plugin since Adapt v2.0 came out so I guess the sprite sheet was something in an older version of the theme. Will see about getting this changed, in the mean time - here's the file:
![adapt-sprite-sheet-48-green](https://cloud.githubusercontent.com/assets/1249597/19472713/419ff37e-9520-11e6-9d92-cf9d318ede01.png)
